name: "RoboFont Extension builder"
description: "Validate and build RoboFont extensions from repository and save it as a release."

runs:
  using: 
  steps: 
    - name: Validate RoboFont Extension
      if: always()
      run: |
        echo "validate extension"
        
    - name: Build RoboFont Extension
      run: |
        echo "build RoboFont Extension"
